Search.appendIndex(
    [
                {
            "fqsen": "\\TextControl\\ReportingCloud\\AbstractReportingCloud",
            "name": "AbstractReportingCloud",
            "summary": "Abstract\u0020ReportingCloud",
            "url": "classes/TextControl-ReportingCloud-AbstractReportingCloud.html"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\AbstractReportingCloud\u003A\u003AgetApiKey\u0028\u0029",
            "name": "getApiKey",
            "summary": "Return\u0020the\u0020API\u0020key",
            "url": "classes/TextControl-ReportingCloud-AbstractReportingCloud.html#method_getApiKey"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\AbstractReportingCloud\u003A\u003AsetApiKey\u0028\u0029",
            "name": "setApiKey",
            "summary": "Set\u0020the\u0020API\u0020key",
            "url": "classes/TextControl-ReportingCloud-AbstractReportingCloud.html#method_setApiKey"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\AbstractReportingCloud\u003A\u003AgetUsername\u0028\u0029",
            "name": "getUsername",
            "summary": "Return\u0020the\u0020username",
            "url": "classes/TextControl-ReportingCloud-AbstractReportingCloud.html#method_getUsername"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\AbstractReportingCloud\u003A\u003AsetUsername\u0028\u0029",
            "name": "setUsername",
            "summary": "Set\u0020the\u0020username",
            "url": "classes/TextControl-ReportingCloud-AbstractReportingCloud.html#method_setUsername"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\AbstractReportingCloud\u003A\u003AgetPassword\u0028\u0029",
            "name": "getPassword",
            "summary": "Return\u0020the\u0020password",
            "url": "classes/TextControl-ReportingCloud-AbstractReportingCloud.html#method_getPassword"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\AbstractReportingCloud\u003A\u003AsetPassword\u0028\u0029",
            "name": "setPassword",
            "summary": "Set\u0020the\u0020password",
            "url": "classes/TextControl-ReportingCloud-AbstractReportingCloud.html#method_setPassword"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\AbstractReportingCloud\u003A\u003AgetBaseUri\u0028\u0029",
            "name": "getBaseUri",
            "summary": "Return\u0020the\u0020base\u0020URI\u0020of\u0020the\u0020backend\u0020web\u0020service",
            "url": "classes/TextControl-ReportingCloud-AbstractReportingCloud.html#method_getBaseUri"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\AbstractReportingCloud\u003A\u003AsetBaseUri\u0028\u0029",
            "name": "setBaseUri",
            "summary": "Set\u0020the\u0020base\u0020URI\u0020of\u0020the\u0020backend\u0020web\u0020service",
            "url": "classes/TextControl-ReportingCloud-AbstractReportingCloud.html#method_setBaseUri"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\AbstractReportingCloud\u003A\u003AgetDebug\u0028\u0029",
            "name": "getDebug",
            "summary": "Return\u0020the\u0020debug\u0020flag",
            "url": "classes/TextControl-ReportingCloud-AbstractReportingCloud.html#method_getDebug"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\AbstractReportingCloud\u003A\u003AsetDebug\u0028\u0029",
            "name": "setDebug",
            "summary": "Set\u0020the\u0020debug\u0020flag",
            "url": "classes/TextControl-ReportingCloud-AbstractReportingCloud.html#method_setDebug"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\AbstractReportingCloud\u003A\u003AgetTest\u0028\u0029",
            "name": "getTest",
            "summary": "Return\u0020the\u0020test\u0020flag",
            "url": "classes/TextControl-ReportingCloud-AbstractReportingCloud.html#method_getTest"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\AbstractReportingCloud\u003A\u003AsetTest\u0028\u0029",
            "name": "setTest",
            "summary": "Set\u0020the\u0020test\u0020flag",
            "url": "classes/TextControl-ReportingCloud-AbstractReportingCloud.html#method_setTest"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\AbstractReportingCloud\u003A\u003AgetTimeout\u0028\u0029",
            "name": "getTimeout",
            "summary": "Get\u0020the\u0020timeout\u0020\u0028in\u0020seconds\u0029\u0020of\u0020the\u0020backend\u0020web\u0020service",
            "url": "classes/TextControl-ReportingCloud-AbstractReportingCloud.html#method_getTimeout"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\AbstractReportingCloud\u003A\u003AsetTimeout\u0028\u0029",
            "name": "setTimeout",
            "summary": "Set\u0020the\u0020timeout\u0020\u0028in\u0020seconds\u0029\u0020of\u0020the\u0020backend\u0020web\u0020service",
            "url": "classes/TextControl-ReportingCloud-AbstractReportingCloud.html#method_setTimeout"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\AbstractReportingCloud\u003A\u003AgetVersion\u0028\u0029",
            "name": "getVersion",
            "summary": "Get\u0020the\u0020version\u0020string\u0020of\u0020the\u0020backend\u0020web\u0020service",
            "url": "classes/TextControl-ReportingCloud-AbstractReportingCloud.html#method_getVersion"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\AbstractReportingCloud\u003A\u003AsetVersion\u0028\u0029",
            "name": "setVersion",
            "summary": "Set\u0020the\u0020version\u0020string\u0020of\u0020the\u0020backend\u0020web\u0020service",
            "url": "classes/TextControl-ReportingCloud-AbstractReportingCloud.html#method_setVersion"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\AbstractReportingCloud\u003A\u003AgetClient\u0028\u0029",
            "name": "getClient",
            "summary": "Return\u0020the\u0020REST\u0020client\u0020of\u0020the\u0020backend\u0020web\u0020service",
            "url": "classes/TextControl-ReportingCloud-AbstractReportingCloud.html#method_getClient"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\AbstractReportingCloud\u003A\u003AsetClient\u0028\u0029",
            "name": "setClient",
            "summary": "Set\u0020the\u0020REST\u0020client\u0020of\u0020the\u0020backend\u0020web\u0020service",
            "url": "classes/TextControl-ReportingCloud-AbstractReportingCloud.html#method_setClient"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\AbstractReportingCloud\u003A\u003Arequest\u0028\u0029",
            "name": "request",
            "summary": "Request\u0020the\u0020URI\u0020with\u0020options",
            "url": "classes/TextControl-ReportingCloud-AbstractReportingCloud.html#method_request"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\AbstractReportingCloud\u003A\u003Auri\u0028\u0029",
            "name": "uri",
            "summary": "Construct\u0020URI\u0020with\u0020version\u0020number",
            "url": "classes/TextControl-ReportingCloud-AbstractReportingCloud.html#method_uri"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\AbstractReportingCloud\u003A\u003AgetAuthorizationHeader\u0028\u0029",
            "name": "getAuthorizationHeader",
            "summary": "Return\u0020Authorization\u0020Header,\u0020with\u0020either\u0020API\u0020key\u0020or\u0020username\u0020and\u0020password",
            "url": "classes/TextControl-ReportingCloud-AbstractReportingCloud.html#method_getAuthorizationHeader"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\AbstractReportingCloud\u003A\u003ADEFAULT_DATE_FORMAT",
            "name": "DEFAULT_DATE_FORMAT",
            "summary": "Default\u0020date\/time\u0020format\u0020of\u0020backend\u0020is\u0020\u0027ISO\u00208601\u0027",
            "url": "classes/TextControl-ReportingCloud-AbstractReportingCloud.html#constant_DEFAULT_DATE_FORMAT"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\AbstractReportingCloud\u003A\u003ADEFAULT_TIME_ZONE",
            "name": "DEFAULT_TIME_ZONE",
            "summary": "Default\u0020time\u0020zone\u0020of\u0020backend",
            "url": "classes/TextControl-ReportingCloud-AbstractReportingCloud.html#constant_DEFAULT_TIME_ZONE"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\AbstractReportingCloud\u003A\u003ADEFAULT_BASE_URI",
            "name": "DEFAULT_BASE_URI",
            "summary": "Default\u0020base\u0020URI\u0020of\u0020backend",
            "url": "classes/TextControl-ReportingCloud-AbstractReportingCloud.html#constant_DEFAULT_BASE_URI"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\AbstractReportingCloud\u003A\u003ADOCUMENT_DIVIDER_NONE",
            "name": "DOCUMENT_DIVIDER_NONE",
            "summary": "Document\u0020divider\u0020\u002D\u0020none",
            "url": "classes/TextControl-ReportingCloud-AbstractReportingCloud.html#constant_DOCUMENT_DIVIDER_NONE"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\AbstractReportingCloud\u003A\u003ADOCUMENT_DIVIDER_NEW_PARAGRAPH",
            "name": "DOCUMENT_DIVIDER_NEW_PARAGRAPH",
            "summary": "Document\u0020divider\u0020\u002D\u0020new\u0020paragraph",
            "url": "classes/TextControl-ReportingCloud-AbstractReportingCloud.html#constant_DOCUMENT_DIVIDER_NEW_PARAGRAPH"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\AbstractReportingCloud\u003A\u003ADOCUMENT_DIVIDER_NEW_SECTION",
            "name": "DOCUMENT_DIVIDER_NEW_SECTION",
            "summary": "Document\u0020divider\u0020\u002D\u0020new\u0020section",
            "url": "classes/TextControl-ReportingCloud-AbstractReportingCloud.html#constant_DOCUMENT_DIVIDER_NEW_SECTION"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\AbstractReportingCloud\u003A\u003AFILE_FORMAT_DOC",
            "name": "FILE_FORMAT_DOC",
            "summary": "DOC\u0020file\u0020format",
            "url": "classes/TextControl-ReportingCloud-AbstractReportingCloud.html#constant_FILE_FORMAT_DOC"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\AbstractReportingCloud\u003A\u003AFILE_FORMAT_DOCX",
            "name": "FILE_FORMAT_DOCX",
            "summary": "DOCX\u0020file\u0020format",
            "url": "classes/TextControl-ReportingCloud-AbstractReportingCloud.html#constant_FILE_FORMAT_DOCX"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\AbstractReportingCloud\u003A\u003AFILE_FORMAT_HTML",
            "name": "FILE_FORMAT_HTML",
            "summary": "HTML\u0020file\u0020format",
            "url": "classes/TextControl-ReportingCloud-AbstractReportingCloud.html#constant_FILE_FORMAT_HTML"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\AbstractReportingCloud\u003A\u003AFILE_FORMAT_PDF",
            "name": "FILE_FORMAT_PDF",
            "summary": "PDF\u0020file\u0020format",
            "url": "classes/TextControl-ReportingCloud-AbstractReportingCloud.html#constant_FILE_FORMAT_PDF"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\AbstractReportingCloud\u003A\u003AFILE_FORMAT_PDFA",
            "name": "FILE_FORMAT_PDFA",
            "summary": "PDF\/A\u0020file\u0020format",
            "url": "classes/TextControl-ReportingCloud-AbstractReportingCloud.html#constant_FILE_FORMAT_PDFA"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\AbstractReportingCloud\u003A\u003AFILE_FORMAT_RTF",
            "name": "FILE_FORMAT_RTF",
            "summary": "RTF\u0020file\u0020format",
            "url": "classes/TextControl-ReportingCloud-AbstractReportingCloud.html#constant_FILE_FORMAT_RTF"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\AbstractReportingCloud\u003A\u003AFILE_FORMAT_TX",
            "name": "FILE_FORMAT_TX",
            "summary": "TX\u0020\u0028Text\u0020Control\u0029\u0020file\u0020format",
            "url": "classes/TextControl-ReportingCloud-AbstractReportingCloud.html#constant_FILE_FORMAT_TX"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\AbstractReportingCloud\u003A\u003AFILE_FORMAT_TXT",
            "name": "FILE_FORMAT_TXT",
            "summary": "Pure\u0020text\u0020file\u0020format",
            "url": "classes/TextControl-ReportingCloud-AbstractReportingCloud.html#constant_FILE_FORMAT_TXT"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\AbstractReportingCloud\u003A\u003AFILE_FORMAT_BMP",
            "name": "FILE_FORMAT_BMP",
            "summary": "Bitmap\u0020file\u0020format",
            "url": "classes/TextControl-ReportingCloud-AbstractReportingCloud.html#constant_FILE_FORMAT_BMP"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\AbstractReportingCloud\u003A\u003AFILE_FORMAT_GIF",
            "name": "FILE_FORMAT_GIF",
            "summary": "GIF\u0020file\u0020format",
            "url": "classes/TextControl-ReportingCloud-AbstractReportingCloud.html#constant_FILE_FORMAT_GIF"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\AbstractReportingCloud\u003A\u003AFILE_FORMAT_JPG",
            "name": "FILE_FORMAT_JPG",
            "summary": "JPEG\u0020file\u0020format",
            "url": "classes/TextControl-ReportingCloud-AbstractReportingCloud.html#constant_FILE_FORMAT_JPG"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\AbstractReportingCloud\u003A\u003AFILE_FORMAT_PNG",
            "name": "FILE_FORMAT_PNG",
            "summary": "PNG\u0020file\u0020format",
            "url": "classes/TextControl-ReportingCloud-AbstractReportingCloud.html#constant_FILE_FORMAT_PNG"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\AbstractReportingCloud\u003A\u003AFILE_FORMAT_XLSX",
            "name": "FILE_FORMAT_XLSX",
            "summary": "XLSX\u0020file\u0020format",
            "url": "classes/TextControl-ReportingCloud-AbstractReportingCloud.html#constant_FILE_FORMAT_XLSX"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\AbstractReportingCloud\u003A\u003ATRACKED_CHANGE_INSERTED_TEXT",
            "name": "TRACKED_CHANGE_INSERTED_TEXT",
            "summary": "InsertedText\u0020tracked\u0020change",
            "url": "classes/TextControl-ReportingCloud-AbstractReportingCloud.html#constant_TRACKED_CHANGE_INSERTED_TEXT"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\AbstractReportingCloud\u003A\u003ATRACKED_CHANGE_DELETED_TEXT",
            "name": "TRACKED_CHANGE_DELETED_TEXT",
            "summary": "DeletedText\u0020tracked\u0020change",
            "url": "classes/TextControl-ReportingCloud-AbstractReportingCloud.html#constant_TRACKED_CHANGE_DELETED_TEXT"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\AbstractReportingCloud\u003A\u003AHIGHLIGHT_MODE_NEVER",
            "name": "HIGHLIGHT_MODE_NEVER",
            "summary": "Never\u0020highlight\u0020mode",
            "url": "classes/TextControl-ReportingCloud-AbstractReportingCloud.html#constant_HIGHLIGHT_MODE_NEVER"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\AbstractReportingCloud\u003A\u003AHIGHLIGHT_MODE_ACTIVATED",
            "name": "HIGHLIGHT_MODE_ACTIVATED",
            "summary": "Activated\u0020highlight\u0020mode",
            "url": "classes/TextControl-ReportingCloud-AbstractReportingCloud.html#constant_HIGHLIGHT_MODE_ACTIVATED"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\AbstractReportingCloud\u003A\u003AHIGHLIGHT_MODE_ALWAYS",
            "name": "HIGHLIGHT_MODE_ALWAYS",
            "summary": "Always\u0020highlight\u0020mode",
            "url": "classes/TextControl-ReportingCloud-AbstractReportingCloud.html#constant_HIGHLIGHT_MODE_ALWAYS"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\AbstractReportingCloud\u003A\u003AFILE_FORMATS_IMAGE",
            "name": "FILE_FORMATS_IMAGE",
            "summary": "Image\u0020file\u0020formats",
            "url": "classes/TextControl-ReportingCloud-AbstractReportingCloud.html#constant_FILE_FORMATS_IMAGE"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\AbstractReportingCloud\u003A\u003AFILE_FORMATS_TEMPLATE",
            "name": "FILE_FORMATS_TEMPLATE",
            "summary": "Template\u0020file\u0020formats",
            "url": "classes/TextControl-ReportingCloud-AbstractReportingCloud.html#constant_FILE_FORMATS_TEMPLATE"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\AbstractReportingCloud\u003A\u003AFILE_FORMATS_DOCUMENT",
            "name": "FILE_FORMATS_DOCUMENT",
            "summary": "Document\u0020file\u0020formats",
            "url": "classes/TextControl-ReportingCloud-AbstractReportingCloud.html#constant_FILE_FORMATS_DOCUMENT"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\AbstractReportingCloud\u003A\u003AFILE_FORMATS_RETURN",
            "name": "FILE_FORMATS_RETURN",
            "summary": "Return\u0020file\u0020formats",
            "url": "classes/TextControl-ReportingCloud-AbstractReportingCloud.html#constant_FILE_FORMATS_RETURN"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\AbstractReportingCloud\u003A\u003ADEFAULT_DEBUG",
            "name": "DEFAULT_DEBUG",
            "summary": "Default\u0020debug\u0020flag\u0020of\u0020REST\u0020client",
            "url": "classes/TextControl-ReportingCloud-AbstractReportingCloud.html#constant_DEFAULT_DEBUG"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\AbstractReportingCloud\u003A\u003ADEFAULT_TEST",
            "name": "DEFAULT_TEST",
            "summary": "Default\u0020test\u0020flag\u0020of\u0020backend",
            "url": "classes/TextControl-ReportingCloud-AbstractReportingCloud.html#constant_DEFAULT_TEST"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\AbstractReportingCloud\u003A\u003ADEFAULT_TIMEOUT",
            "name": "DEFAULT_TIMEOUT",
            "summary": "Default\u0020timeout\u0020of\u0020backend\u0020in\u0020seconds",
            "url": "classes/TextControl-ReportingCloud-AbstractReportingCloud.html#constant_DEFAULT_TIMEOUT"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\AbstractReportingCloud\u003A\u003ADEFAULT_VERSION",
            "name": "DEFAULT_VERSION",
            "summary": "Default\u0020version\u0020string\u0020of\u0020backend",
            "url": "classes/TextControl-ReportingCloud-AbstractReportingCloud.html#constant_DEFAULT_VERSION"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\AbstractReportingCloud\u003A\u003A\u0024apiKey",
            "name": "apiKey",
            "summary": "Backend\u0020API\u0020key",
            "url": "classes/TextControl-ReportingCloud-AbstractReportingCloud.html#property_apiKey"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\AbstractReportingCloud\u003A\u003A\u0024username",
            "name": "username",
            "summary": "Backend\u0020username",
            "url": "classes/TextControl-ReportingCloud-AbstractReportingCloud.html#property_username"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\AbstractReportingCloud\u003A\u003A\u0024password",
            "name": "password",
            "summary": "Backend\u0020password",
            "url": "classes/TextControl-ReportingCloud-AbstractReportingCloud.html#property_password"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\AbstractReportingCloud\u003A\u003A\u0024baseUri",
            "name": "baseUri",
            "summary": "Backend\u0020base\u0020URI",
            "url": "classes/TextControl-ReportingCloud-AbstractReportingCloud.html#property_baseUri"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\AbstractReportingCloud\u003A\u003A\u0024debug",
            "name": "debug",
            "summary": "Debug\u0020flag\u0020of\u0020REST\u0020client",
            "url": "classes/TextControl-ReportingCloud-AbstractReportingCloud.html#property_debug"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\AbstractReportingCloud\u003A\u003A\u0024test",
            "name": "test",
            "summary": "When\u0020true,\u0020API\u0020call\u0020does\u0020not\u0020count\u0020against\u0020quota\n\u0022TEST\u0020MODE\u0022\u0020watermark\u0020is\u0020added\u0020to\u0020document",
            "url": "classes/TextControl-ReportingCloud-AbstractReportingCloud.html#property_test"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\AbstractReportingCloud\u003A\u003A\u0024timeout",
            "name": "timeout",
            "summary": "Backend\u0020timeout\u0020in\u0020seconds",
            "url": "classes/TextControl-ReportingCloud-AbstractReportingCloud.html#property_timeout"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\AbstractReportingCloud\u003A\u003A\u0024version",
            "name": "version",
            "summary": "Backend\u0020version\u0020string",
            "url": "classes/TextControl-ReportingCloud-AbstractReportingCloud.html#property_version"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\AbstractReportingCloud\u003A\u003A\u0024client",
            "name": "client",
            "summary": "REST\u0020client\u0020to\u0020backend",
            "url": "classes/TextControl-ReportingCloud-AbstractReportingCloud.html#property_client"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Assert\\AbstractAssert",
            "name": "AbstractAssert",
            "summary": "Abstract\u0020AbstractAssert",
            "url": "classes/TextControl-ReportingCloud-Assert-AbstractAssert.html"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Assert\\Assert",
            "name": "Assert",
            "summary": "Abstract\u0020AbstractAssert",
            "url": "classes/TextControl-ReportingCloud-Assert-Assert.html"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Assert\\AssertApiKeyTrait",
            "name": "AssertApiKeyTrait",
            "summary": "Trait\u0020AssertApiKeyTrait",
            "url": "classes/TextControl-ReportingCloud-Assert-AssertApiKeyTrait.html"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Assert\\AssertApiKeyTrait\u003A\u003AassertApiKey\u0028\u0029",
            "name": "assertApiKey",
            "summary": "Check\u0020value\u0020is\u0020a\u0020syntactically\u0020valid\u0020API\u0020key",
            "url": "classes/TextControl-ReportingCloud-Assert-AssertApiKeyTrait.html#method_assertApiKey"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Assert\\AssertApiKeyTrait\u003A\u003A\u0024apiKeyMinLength",
            "name": "apiKeyMinLength",
            "summary": "Minimum\u0020length\u0020of\u0020API\u0020key",
            "url": "classes/TextControl-ReportingCloud-Assert-AssertApiKeyTrait.html#property_apiKeyMinLength"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Assert\\AssertApiKeyTrait\u003A\u003A\u0024apiKeyMaxLength",
            "name": "apiKeyMaxLength",
            "summary": "Maximum\u0020length\u0020of\u0020API\u0020key",
            "url": "classes/TextControl-ReportingCloud-Assert-AssertApiKeyTrait.html#property_apiKeyMaxLength"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Assert\\AssertBase64DataTrait",
            "name": "AssertBase64DataTrait",
            "summary": "Trait\u0020AssertBase64DataTrait",
            "url": "classes/TextControl-ReportingCloud-Assert-AssertBase64DataTrait.html"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Assert\\AssertBase64DataTrait\u003A\u003AassertBase64Data\u0028\u0029",
            "name": "assertBase64Data",
            "summary": "Check\u0020value\u0020is\u0020valid\u0020base64\u0020encoded\u0020data",
            "url": "classes/TextControl-ReportingCloud-Assert-AssertBase64DataTrait.html#method_assertBase64Data"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Assert\\AssertBaseUriTrait",
            "name": "AssertBaseUriTrait",
            "summary": "Trait\u0020AssertBaseUriTrait",
            "url": "classes/TextControl-ReportingCloud-Assert-AssertBaseUriTrait.html"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Assert\\AssertBaseUriTrait\u003A\u003AassertBaseUri\u0028\u0029",
            "name": "assertBaseUri",
            "summary": "Check\u0020value\u0020is\u0020a\u0020known\u0020base\u0020URI",
            "url": "classes/TextControl-ReportingCloud-Assert-AssertBaseUriTrait.html#method_assertBaseUri"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Assert\\AssertCultureTrait",
            "name": "AssertCultureTrait",
            "summary": "Trait\u0020AssertLanguageTrait",
            "url": "classes/TextControl-ReportingCloud-Assert-AssertCultureTrait.html"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Assert\\AssertCultureTrait\u003A\u003AassertCulture\u0028\u0029",
            "name": "assertCulture",
            "summary": "Check\u0020value\u0020is\u0020a\u0020valid\u0020culture",
            "url": "classes/TextControl-ReportingCloud-Assert-AssertCultureTrait.html#method_assertCulture"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Assert\\AssertCultureTrait\u003A\u003AgetCulturesFilename\u0028\u0029",
            "name": "getCulturesFilename",
            "summary": "Return\u0020the\u0020filename,\u0020containing\u0020cultures\u0020array",
            "url": "classes/TextControl-ReportingCloud-Assert-AssertCultureTrait.html#method_getCulturesFilename"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Assert\\AssertCultureTrait\u003A\u003AgetCultures\u0028\u0029",
            "name": "getCultures",
            "summary": "Return\u0020cultures\u0020array",
            "url": "classes/TextControl-ReportingCloud-Assert-AssertCultureTrait.html#method_getCultures"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Assert\\AssertDateTimeTrait",
            "name": "AssertDateTimeTrait",
            "summary": "Trait\u0020AssertDateTimeTrait",
            "url": "classes/TextControl-ReportingCloud-Assert-AssertDateTimeTrait.html"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Assert\\AssertDateTimeTrait\u003A\u003AassertDateTime\u0028\u0029",
            "name": "assertDateTime",
            "summary": "Check\u0020value\u0020is\u0020a\u0020valid\u0020DateTime\u0020string",
            "url": "classes/TextControl-ReportingCloud-Assert-AssertDateTimeTrait.html#method_assertDateTime"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Assert\\AssertDateTimeTrait\u003A\u003AgetDateTimeLength\u0028\u0029",
            "name": "getDateTimeLength",
            "summary": "Get\u0020the\u0020length\u0020of\u0020the\u0020required\u0020dateTime\u0020string",
            "url": "classes/TextControl-ReportingCloud-Assert-AssertDateTimeTrait.html#method_getDateTimeLength"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Assert\\AssertDocumentDividerTrait",
            "name": "AssertDocumentDividerTrait",
            "summary": "Trait\u0020DocumentDividerTrait",
            "url": "classes/TextControl-ReportingCloud-Assert-AssertDocumentDividerTrait.html"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Assert\\AssertDocumentDividerTrait\u003A\u003AassertDocumentDivider\u0028\u0029",
            "name": "assertDocumentDivider",
            "summary": "Check\u0020value\u0020is\u0020a\u0020valid\u0020document\u0020divider",
            "url": "classes/TextControl-ReportingCloud-Assert-AssertDocumentDividerTrait.html#method_assertDocumentDivider"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Assert\\AssertDocumentDividerTrait\u003A\u003AgetDocumentDividers\u0028\u0029",
            "name": "getDocumentDividers",
            "summary": "Return\u0020document\u0020dividers\u0020array",
            "url": "classes/TextControl-ReportingCloud-Assert-AssertDocumentDividerTrait.html#method_getDocumentDividers"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Assert\\AssertDocumentExtensionTrait",
            "name": "AssertDocumentExtensionTrait",
            "summary": "Trait\u0020AssertDocumentExtensionTrait",
            "url": "classes/TextControl-ReportingCloud-Assert-AssertDocumentExtensionTrait.html"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Assert\\AssertDocumentExtensionTrait\u003A\u003AassertDocumentExtension\u0028\u0029",
            "name": "assertDocumentExtension",
            "summary": "Check\u0020value\u0020is\u0020a\u0020valid\u0020document\u0020format\u0020extension",
            "url": "classes/TextControl-ReportingCloud-Assert-AssertDocumentExtensionTrait.html#method_assertDocumentExtension"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Assert\\AssertDocumentThumbnailExtensionTrait",
            "name": "AssertDocumentThumbnailExtensionTrait",
            "summary": "Trait\u0020AssertDocumentThumbnailExtensionTrait",
            "url": "classes/TextControl-ReportingCloud-Assert-AssertDocumentThumbnailExtensionTrait.html"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Assert\\AssertDocumentThumbnailExtensionTrait\u003A\u003AassertDocumentThumbnailExtension\u0028\u0029",
            "name": "assertDocumentThumbnailExtension",
            "summary": "Check\u0020value\u0020is\u0020a\u0020valid\u0020document\u0020thumbnail\u0020format\u0020extension",
            "url": "classes/TextControl-ReportingCloud-Assert-AssertDocumentThumbnailExtensionTrait.html#method_assertDocumentThumbnailExtension"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Assert\\AssertFilenameExistsTrait",
            "name": "AssertFilenameExistsTrait",
            "summary": "Trait\u0020AssertFilenameExistsTrait",
            "url": "classes/TextControl-ReportingCloud-Assert-AssertFilenameExistsTrait.html"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Assert\\AssertFilenameExistsTrait\u003A\u003AassertFilenameExists\u0028\u0029",
            "name": "assertFilenameExists",
            "summary": "Check\u0020filename\u0020exists\u0020and\u0020is\u0020readable",
            "url": "classes/TextControl-ReportingCloud-Assert-AssertFilenameExistsTrait.html#method_assertFilenameExists"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Assert\\AssertImageFormatTrait",
            "name": "AssertImageFormatTrait",
            "summary": "Trait\u0020AssertImageFormatTrait",
            "url": "classes/TextControl-ReportingCloud-Assert-AssertImageFormatTrait.html"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Assert\\AssertImageFormatTrait\u003A\u003AassertImageFormat\u0028\u0029",
            "name": "assertImageFormat",
            "summary": "Check\u0020value\u0020is\u0020valid\u0020image\u0020format\u0020extension",
            "url": "classes/TextControl-ReportingCloud-Assert-AssertImageFormatTrait.html#method_assertImageFormat"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Assert\\AssertLanguageTrait",
            "name": "AssertLanguageTrait",
            "summary": "Trait\u0020AssertLanguageTrait",
            "url": "classes/TextControl-ReportingCloud-Assert-AssertLanguageTrait.html"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Assert\\AssertLanguageTrait\u003A\u003AassertLanguage\u0028\u0029",
            "name": "assertLanguage",
            "summary": "Check\u0020value\u0020is\u0020a\u0020valid\u0020language",
            "url": "classes/TextControl-ReportingCloud-Assert-AssertLanguageTrait.html#method_assertLanguage"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Assert\\AssertLanguageTrait\u003A\u003AgetDictionariesFilename\u0028\u0029",
            "name": "getDictionariesFilename",
            "summary": "Return\u0020the\u0020filename,\u0020containing\u0020languages\u0020aka\u0020dictionaries\u0020array",
            "url": "classes/TextControl-ReportingCloud-Assert-AssertLanguageTrait.html#method_getDictionariesFilename"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Assert\\AssertLanguageTrait\u003A\u003AgetDictionaries\u0028\u0029",
            "name": "getDictionaries",
            "summary": "Return\u0020languages\u0020aka\u0020dictionaries\u0020array",
            "url": "classes/TextControl-ReportingCloud-Assert-AssertLanguageTrait.html#method_getDictionaries"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Assert\\AssertOneOfTrait",
            "name": "AssertOneOfTrait",
            "summary": "Trait\u0020AssertOneOfTrait",
            "url": "classes/TextControl-ReportingCloud-Assert-AssertOneOfTrait.html"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Assert\\AssertOneOfTrait\u003A\u003AassertOneOf\u0028\u0029",
            "name": "assertOneOf",
            "summary": "Check\u0020value\u0020is\u0020in\u0020values",
            "url": "classes/TextControl-ReportingCloud-Assert-AssertOneOfTrait.html#method_assertOneOf"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Assert\\AssertPageTrait",
            "name": "AssertPageTrait",
            "summary": "Trait\u0020AssertPageTrait",
            "url": "classes/TextControl-ReportingCloud-Assert-AssertPageTrait.html"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Assert\\AssertPageTrait\u003A\u003AassertPage\u0028\u0029",
            "name": "assertPage",
            "summary": "Check\u0020value\u0020is\u0020a\u0020valid\u0020page\u0020number",
            "url": "classes/TextControl-ReportingCloud-Assert-AssertPageTrait.html#method_assertPage"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Assert\\AssertPageTrait\u003A\u003A\u0024pageMin",
            "name": "pageMin",
            "summary": "Minimum\u0020page\u0020number",
            "url": "classes/TextControl-ReportingCloud-Assert-AssertPageTrait.html#property_pageMin"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Assert\\AssertPageTrait\u003A\u003A\u0024pageMax",
            "name": "pageMax",
            "summary": "Maximum\u0020page\u0020number\u0020\u0028PHP_INT_MAX\u0029",
            "url": "classes/TextControl-ReportingCloud-Assert-AssertPageTrait.html#property_pageMax"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Assert\\AssertRangeTrait",
            "name": "AssertRangeTrait",
            "summary": "Trait\u0020AssertRangeTrait",
            "url": "classes/TextControl-ReportingCloud-Assert-AssertRangeTrait.html"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Assert\\AssertRangeTrait\u003A\u003AassertRange\u0028\u0029",
            "name": "assertRange",
            "summary": "Check\u0020value\u0020is\u0020in\u0020range\u0020min..max",
            "url": "classes/TextControl-ReportingCloud-Assert-AssertRangeTrait.html#method_assertRange"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Assert\\AssertRemoveTrait",
            "name": "AssertRemoveTrait",
            "summary": "Trait\u0020AssertRemoveTrait",
            "url": "classes/TextControl-ReportingCloud-Assert-AssertRemoveTrait.html"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Assert\\AssertRemoveTrait\u003A\u003AassertRemove\u0028\u0029",
            "name": "assertRemove",
            "summary": "Check\u0020value\u0020is\u0020a\u0020\u0022remove_\u002A\u0022\u0020value",
            "url": "classes/TextControl-ReportingCloud-Assert-AssertRemoveTrait.html#method_assertRemove"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Assert\\AssertReturnFormatTrait",
            "name": "AssertReturnFormatTrait",
            "summary": "Trait\u0020AssertReturnFormatTrait",
            "url": "classes/TextControl-ReportingCloud-Assert-AssertReturnFormatTrait.html"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Assert\\AssertReturnFormatTrait\u003A\u003AassertReturnFormat\u0028\u0029",
            "name": "assertReturnFormat",
            "summary": "Check\u0020value\u0020is\u0020a\u0020valid\u0020return\u0020format\u0020extension",
            "url": "classes/TextControl-ReportingCloud-Assert-AssertReturnFormatTrait.html#method_assertReturnFormat"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Assert\\AssertTemplateExtensionTrait",
            "name": "AssertTemplateExtensionTrait",
            "summary": "Trait\u0020AssertTemplateExtensionTrait",
            "url": "classes/TextControl-ReportingCloud-Assert-AssertTemplateExtensionTrait.html"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Assert\\AssertTemplateExtensionTrait\u003A\u003AassertTemplateExtension\u0028\u0029",
            "name": "assertTemplateExtension",
            "summary": "Check\u0020value\u0020is\u0020a\u0020valid\u0020template\u0020extension",
            "url": "classes/TextControl-ReportingCloud-Assert-AssertTemplateExtensionTrait.html#method_assertTemplateExtension"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Assert\\AssertTemplateFormatTrait",
            "name": "AssertTemplateFormatTrait",
            "summary": "Trait\u0020AssertTemplateFormatTrait",
            "url": "classes/TextControl-ReportingCloud-Assert-AssertTemplateFormatTrait.html"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Assert\\AssertTemplateFormatTrait\u003A\u003AassertTemplateFormat\u0028\u0029",
            "name": "assertTemplateFormat",
            "summary": "Check\u0020value\u0020is\u0020a\u0020valid\u0020template\u0020format",
            "url": "classes/TextControl-ReportingCloud-Assert-AssertTemplateFormatTrait.html#method_assertTemplateFormat"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Assert\\AssertTemplateNameTrait",
            "name": "AssertTemplateNameTrait",
            "summary": "Trait\u0020AssertTemplateNameTrait",
            "url": "classes/TextControl-ReportingCloud-Assert-AssertTemplateNameTrait.html"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Assert\\AssertTemplateNameTrait\u003A\u003AassertTemplateName\u0028\u0029",
            "name": "assertTemplateName",
            "summary": "Check\u0020value\u0020is\u0020a\u0020valid\u0020template\u0020name",
            "url": "classes/TextControl-ReportingCloud-Assert-AssertTemplateNameTrait.html#method_assertTemplateName"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Assert\\AssertTimestampTrait",
            "name": "AssertTimestampTrait",
            "summary": "Trait\u0020AssertTimestampTrait",
            "url": "classes/TextControl-ReportingCloud-Assert-AssertTimestampTrait.html"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Assert\\AssertTimestampTrait\u003A\u003AassertTimestamp\u0028\u0029",
            "name": "assertTimestamp",
            "summary": "Check\u0020value\u0020is\u0020a\u0020valid\u0020timestamp",
            "url": "classes/TextControl-ReportingCloud-Assert-AssertTimestampTrait.html#method_assertTimestamp"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Assert\\AssertTimestampTrait\u003A\u003A\u0024timestampMin",
            "name": "timestampMin",
            "summary": "Minimum\u0020timestamp\u0020\u0028EPOC\u0029",
            "url": "classes/TextControl-ReportingCloud-Assert-AssertTimestampTrait.html#property_timestampMin"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Assert\\AssertTimestampTrait\u003A\u003A\u0024timestampMax",
            "name": "timestampMax",
            "summary": "Maximum\u0020timestamp\u0020\u0028PHP_INT_MAX\u0029",
            "url": "classes/TextControl-ReportingCloud-Assert-AssertTimestampTrait.html#property_timestampMax"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Assert\\AssertZoomFactorTrait",
            "name": "AssertZoomFactorTrait",
            "summary": "Trait\u0020AssertZoomFactorTrait",
            "url": "classes/TextControl-ReportingCloud-Assert-AssertZoomFactorTrait.html"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Assert\\AssertZoomFactorTrait\u003A\u003AassertZoomFactor\u0028\u0029",
            "name": "assertZoomFactor",
            "summary": "Check\u0020value\u0020is\u0020a\u0020valid\u0020zoom\u0020factor",
            "url": "classes/TextControl-ReportingCloud-Assert-AssertZoomFactorTrait.html#method_assertZoomFactor"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Assert\\AssertZoomFactorTrait\u003A\u003A\u0024zoomFactorMin",
            "name": "zoomFactorMin",
            "summary": "Minimum\u0020zoom\u0020factor",
            "url": "classes/TextControl-ReportingCloud-Assert-AssertZoomFactorTrait.html#property_zoomFactorMin"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Assert\\AssertZoomFactorTrait\u003A\u003A\u0024zoomFactorMax",
            "name": "zoomFactorMax",
            "summary": "Maximum\u0020zoom\u0020factor",
            "url": "classes/TextControl-ReportingCloud-Assert-AssertZoomFactorTrait.html#property_zoomFactorMax"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Assert\\ValueToStringTrait",
            "name": "ValueToStringTrait",
            "summary": "Trait\u0020ValueToStringTrait",
            "url": "classes/TextControl-ReportingCloud-Assert-ValueToStringTrait.html"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Assert\\ValueToStringTrait\u003A\u003AvalueToString\u0028\u0029",
            "name": "valueToString",
            "summary": "Convert\u0020value\u0020to\u0020string",
            "url": "classes/TextControl-ReportingCloud-Assert-ValueToStringTrait.html#method_valueToString"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\BuildTrait",
            "name": "BuildTrait",
            "summary": "Trait\u0020BuildTrait",
            "url": "classes/TextControl-ReportingCloud-BuildTrait.html"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\BuildTrait\u003A\u003AbuildPropertyMapArray\u0028\u0029",
            "name": "buildPropertyMapArray",
            "summary": "Using\u0020the\u0020passed\u0020propertyMap,\u0020recursively\u0020build\u0020array",
            "url": "classes/TextControl-ReportingCloud-BuildTrait.html#method_buildPropertyMapArray"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\BuildTrait\u003A\u003AbuildDocumentsArray\u0028\u0029",
            "name": "buildDocumentsArray",
            "summary": "Using\u0020passed\u0020documentsData\u0020array,\u0020build\u0020array\u0020for\u0020backend",
            "url": "classes/TextControl-ReportingCloud-BuildTrait.html#method_buildDocumentsArray"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\BuildTrait\u003A\u003AbuildDocumentSettingsArray\u0028\u0029",
            "name": "buildDocumentSettingsArray",
            "summary": "Using\u0020passed\u0020documentsSettings\u0020array,\u0020build\u0020array\u0020for\u0020backend",
            "url": "classes/TextControl-ReportingCloud-BuildTrait.html#method_buildDocumentSettingsArray"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\BuildTrait\u003A\u003AbuildMergeSettingsArray\u0028\u0029",
            "name": "buildMergeSettingsArray",
            "summary": "Using\u0020passed\u0020mergeSettings\u0020array,\u0020build\u0020array\u0020for\u0020backend",
            "url": "classes/TextControl-ReportingCloud-BuildTrait.html#method_buildMergeSettingsArray"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\BuildTrait\u003A\u003AbuildFindAndReplaceDataArray\u0028\u0029",
            "name": "buildFindAndReplaceDataArray",
            "summary": "Using\u0020passed\u0020findAndReplaceData\u0020associative\u0020array\u0020\u0028key\u002Dvalue\u0029,\u0020build\u0020array\u0020for\u0020backend\u0020\u0028list\u0020of\u0020string\u0020arrays\u0029",
            "url": "classes/TextControl-ReportingCloud-BuildTrait.html#method_buildFindAndReplaceDataArray"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\DeleteTrait",
            "name": "DeleteTrait",
            "summary": "Trait\u0020DeleteTrait",
            "url": "classes/TextControl-ReportingCloud-DeleteTrait.html"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\DeleteTrait\u003A\u003AdeleteApiKey\u0028\u0029",
            "name": "deleteApiKey",
            "summary": "Delete\u0020an\u0020API\u0020key",
            "url": "classes/TextControl-ReportingCloud-DeleteTrait.html#method_deleteApiKey"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\DeleteTrait\u003A\u003AdeleteTemplate\u0028\u0029",
            "name": "deleteTemplate",
            "summary": "Delete\u0020a\u0020template\u0020in\u0020template\u0020storage",
            "url": "classes/TextControl-ReportingCloud-DeleteTrait.html#method_deleteTemplate"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\DeleteTrait\u003A\u003Auri\u0028\u0029",
            "name": "uri",
            "summary": "Construct\u0020URI\u0020with\u0020version\u0020number",
            "url": "classes/TextControl-ReportingCloud-DeleteTrait.html#method_uri"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\DeleteTrait\u003A\u003Arequest\u0028\u0029",
            "name": "request",
            "summary": "Request\u0020the\u0020URI\u0020with\u0020options",
            "url": "classes/TextControl-ReportingCloud-DeleteTrait.html#method_request"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\DeleteTrait\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "Execute\u0020a\u0020DELETE\u0020request\u0020via\u0020REST\u0020client",
            "url": "classes/TextControl-ReportingCloud-DeleteTrait.html#method_delete"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Exception\\ExceptionInterface",
            "name": "ExceptionInterface",
            "summary": "ExceptionInterface",
            "url": "classes/TextControl-ReportingCloud-Exception-ExceptionInterface.html"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Exception\\InvalidArgumentException",
            "name": "InvalidArgumentException",
            "summary": "InvalidArgumentException",
            "url": "classes/TextControl-ReportingCloud-Exception-InvalidArgumentException.html"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Exception\\RuntimeException",
            "name": "RuntimeException",
            "summary": "RuntimeException",
            "url": "classes/TextControl-ReportingCloud-Exception-RuntimeException.html"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Filter\\AbstractFilter",
            "name": "AbstractFilter",
            "summary": "Abstract\u0020AbstractFilter",
            "url": "classes/TextControl-ReportingCloud-Filter-AbstractFilter.html"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Filter\\Filter",
            "name": "Filter",
            "summary": "Abstract\u0020AbstractFilter",
            "url": "classes/TextControl-ReportingCloud-Filter-Filter.html"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Filter\\FilterBooleanToStringTrait",
            "name": "FilterBooleanToStringTrait",
            "summary": "Trait\u0020FilterBooleanToStringTrait",
            "url": "classes/TextControl-ReportingCloud-Filter-FilterBooleanToStringTrait.html"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Filter\\FilterBooleanToStringTrait\u003A\u003AfilterBooleanToString\u0028\u0029",
            "name": "filterBooleanToString",
            "summary": "Convert\u0020bool\u0020true\u0020and\u0020false\u0020to\u0020string\u0020\u0027true\u0027\u0020and\u0020\u0027false\u0027.",
            "url": "classes/TextControl-ReportingCloud-Filter-FilterBooleanToStringTrait.html#method_filterBooleanToString"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Filter\\FilterDateTimeToTimestampTrait",
            "name": "FilterDateTimeToTimestampTrait",
            "summary": "Trait\u0020FilterDateTimeToTimestampTrait",
            "url": "classes/TextControl-ReportingCloud-Filter-FilterDateTimeToTimestampTrait.html"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Filter\\FilterDateTimeToTimestampTrait\u003A\u003AfilterDateTimeToTimestamp\u0028\u0029",
            "name": "filterDateTimeToTimestamp",
            "summary": "Convert\u0020the\u0020date\/time\u0020format\u0020used\u0020by\u0020the\u0020backend\u0020\u0028e.g.\u0020\u00222016\u002D04\u002D15T19\u003A05\u003A18\u002B00\u003A00\u0022\u0029\u0020to\u0020a\u0020UNIX\u0020timestamp.",
            "url": "classes/TextControl-ReportingCloud-Filter-FilterDateTimeToTimestampTrait.html#method_filterDateTimeToTimestamp"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Filter\\FilterTimestampToDateTimeTrait",
            "name": "FilterTimestampToDateTimeTrait",
            "summary": "Trait\u0020FilterTimestampToDateTimeTrait",
            "url": "classes/TextControl-ReportingCloud-Filter-FilterTimestampToDateTimeTrait.html"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Filter\\FilterTimestampToDateTimeTrait\u003A\u003AfilterTimestampToDateTime\u0028\u0029",
            "name": "filterTimestampToDateTime",
            "summary": "Convert\u0020a\u0020UNIX\u0020timestamp\u0020to\u0020the\u0020date\/time\u0020format\u0020used\u0020by\u0020the\u0020backend\u0020\u0028e.g.\u0020\u00222016\u002D04\u002D15T19\u003A05\u003A18\u002B00\u003A00\u0022\u0029.",
            "url": "classes/TextControl-ReportingCloud-Filter-FilterTimestampToDateTimeTrait.html#method_filterTimestampToDateTime"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\GetTrait",
            "name": "GetTrait",
            "summary": "Trait\u0020GetTrait",
            "url": "classes/TextControl-ReportingCloud-GetTrait.html"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\GetTrait\u003A\u003AgetApiKeys\u0028\u0029",
            "name": "getApiKeys",
            "summary": "Return\u0020an\u0020associative\u0020array\u0020of\u0020API\u0020keys\u0020associated\u0020with\u0020the\u0020Reporting\u0020Cloud\u0020account",
            "url": "classes/TextControl-ReportingCloud-GetTrait.html#method_getApiKeys"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\GetTrait\u003A\u003AproofingCheck\u0028\u0029",
            "name": "proofingCheck",
            "summary": "Check\u0020a\u0020corpus\u0020of\u0020text\u0020for\u0020spelling\u0020errors.",
            "url": "classes/TextControl-ReportingCloud-GetTrait.html#method_proofingCheck"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\GetTrait\u003A\u003AgetAvailableDictionaries\u0028\u0029",
            "name": "getAvailableDictionaries",
            "summary": "Return\u0020an\u0020array\u0020of\u0020available\u0020dictionaries\u0020on\u0020the\u0020Reporting\u0020Cloud\u0020service",
            "url": "classes/TextControl-ReportingCloud-GetTrait.html#method_getAvailableDictionaries"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\GetTrait\u003A\u003AgetProofingSuggestions\u0028\u0029",
            "name": "getProofingSuggestions",
            "summary": "Return\u0020an\u0020array\u0020of\u0020suggestions\u0020for\u0020a\u0020misspelled\u0020word",
            "url": "classes/TextControl-ReportingCloud-GetTrait.html#method_getProofingSuggestions"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\GetTrait\u003A\u003AgetTemplateInfo\u0028\u0029",
            "name": "getTemplateInfo",
            "summary": "Return\u0020an\u0020array\u0020of\u0020merge\u0020blocks\u0020and\u0020merge\u0020fields\u0020in\u0020a\u0020template\u0020file\u0020in\u0020template\u0020storage",
            "url": "classes/TextControl-ReportingCloud-GetTrait.html#method_getTemplateInfo"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\GetTrait\u003A\u003AgetTemplateThumbnails\u0028\u0029",
            "name": "getTemplateThumbnails",
            "summary": "Generate\u0020a\u0020thumbnail\u0020image\u0020per\u0020page\u0020of\u0020specified\u0020template\u0020in\u0020template\u0020storage.",
            "url": "classes/TextControl-ReportingCloud-GetTrait.html#method_getTemplateThumbnails"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\GetTrait\u003A\u003AgetTemplateCount\u0028\u0029",
            "name": "getTemplateCount",
            "summary": "Return\u0020the\u0020number\u0020of\u0020templates\u0020in\u0020template\u0020storage",
            "url": "classes/TextControl-ReportingCloud-GetTrait.html#method_getTemplateCount"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\GetTrait\u003A\u003AgetTemplateList\u0028\u0029",
            "name": "getTemplateList",
            "summary": "Return\u0020an\u0020array\u0020properties\u0020for\u0020the\u0020templates\u0020in\u0020template\u0020storage",
            "url": "classes/TextControl-ReportingCloud-GetTrait.html#method_getTemplateList"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\GetTrait\u003A\u003AgetTemplatePageCount\u0028\u0029",
            "name": "getTemplatePageCount",
            "summary": "Return\u0020the\u0020number\u0020of\u0020pages\u0020in\u0020a\u0020template\u0020in\u0020template\u0020storage",
            "url": "classes/TextControl-ReportingCloud-GetTrait.html#method_getTemplatePageCount"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\GetTrait\u003A\u003AtemplateExists\u0028\u0029",
            "name": "templateExists",
            "summary": "Return\u0020true,\u0020if\u0020the\u0020template\u0020exists\u0020in\u0020template\u0020storage",
            "url": "classes/TextControl-ReportingCloud-GetTrait.html#method_templateExists"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\GetTrait\u003A\u003AgetFontList\u0028\u0029",
            "name": "getFontList",
            "summary": "Return\u0020an\u0020array\u0020of\u0020available\u0020fonts\u0020on\u0020the\u0020Reporting\u0020Cloud\u0020service",
            "url": "classes/TextControl-ReportingCloud-GetTrait.html#method_getFontList"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\GetTrait\u003A\u003AgetAccountSettings\u0028\u0029",
            "name": "getAccountSettings",
            "summary": "Return\u0020an\u0020array\u0020properties\u0020for\u0020the\u0020ReportingCloud\u0020account",
            "url": "classes/TextControl-ReportingCloud-GetTrait.html#method_getAccountSettings"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\GetTrait\u003A\u003AdownloadTemplate\u0028\u0029",
            "name": "downloadTemplate",
            "summary": "Download\u0020the\u0020binary\u0020data\u0020of\u0020a\u0020template\u0020from\u0020template\u0020storage",
            "url": "classes/TextControl-ReportingCloud-GetTrait.html#method_downloadTemplate"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\GetTrait\u003A\u003Auri\u0028\u0029",
            "name": "uri",
            "summary": "Construct\u0020URI\u0020with\u0020version\u0020number",
            "url": "classes/TextControl-ReportingCloud-GetTrait.html#method_uri"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\GetTrait\u003A\u003Arequest\u0028\u0029",
            "name": "request",
            "summary": "Request\u0020the\u0020URI\u0020with\u0020options",
            "url": "classes/TextControl-ReportingCloud-GetTrait.html#method_request"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\GetTrait\u003A\u003AbuildPropertyMapArray\u0028\u0029",
            "name": "buildPropertyMapArray",
            "summary": "Using\u0020the\u0020passed\u0020propertyMap,\u0020recursively\u0020build\u0020array",
            "url": "classes/TextControl-ReportingCloud-GetTrait.html#method_buildPropertyMapArray"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\GetTrait\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "Execute\u0020a\u0020GET\u0020request\u0020via\u0020REST\u0020client",
            "url": "classes/TextControl-ReportingCloud-GetTrait.html#method_get"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\PostTrait",
            "name": "PostTrait",
            "summary": "Trait\u0020PostTrait",
            "url": "classes/TextControl-ReportingCloud-PostTrait.html"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\PostTrait\u003A\u003AuploadTemplateFromBase64\u0028\u0029",
            "name": "uploadTemplateFromBase64",
            "summary": "Upload\u0020a\u0020base64\u0020encoded\u0020template\u0020to\u0020template\u0020storage",
            "url": "classes/TextControl-ReportingCloud-PostTrait.html#method_uploadTemplateFromBase64"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\PostTrait\u003A\u003AuploadTemplate\u0028\u0029",
            "name": "uploadTemplate",
            "summary": "Upload\u0020a\u0020template\u0020to\u0020template\u0020storage",
            "url": "classes/TextControl-ReportingCloud-PostTrait.html#method_uploadTemplate"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\PostTrait\u003A\u003AconvertDocument\u0028\u0029",
            "name": "convertDocument",
            "summary": "Convert\u0020a\u0020document\u0020on\u0020the\u0020local\u0020file\u0020system\u0020to\u0020a\u0020different\u0020format",
            "url": "classes/TextControl-ReportingCloud-PostTrait.html#method_convertDocument"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\PostTrait\u003A\u003AmergeDocument\u0028\u0029",
            "name": "mergeDocument",
            "summary": "Merge\u0020data\u0020into\u0020a\u0020template\u0020and\u0020return\u0020an\u0020array\u0020of\u0020binary\u0020data.",
            "url": "classes/TextControl-ReportingCloud-PostTrait.html#method_mergeDocument"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\PostTrait\u003A\u003AappendDocument\u0028\u0029",
            "name": "appendDocument",
            "summary": "Combine\u0020documents\u0020by\u0020appending\u0020them,\u0020divided\u0020by\u0020a\u0020new\u0020section,\u0020paragraph\u0020or\u0020nothing",
            "url": "classes/TextControl-ReportingCloud-PostTrait.html#method_appendDocument"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\PostTrait\u003A\u003AfindAndReplaceDocument\u0028\u0029",
            "name": "findAndReplaceDocument",
            "summary": "Perform\u0020find\u0020and\u0020replace\u0020in\u0020document\u0020and\u0020return\u0020binary\u0020data.",
            "url": "classes/TextControl-ReportingCloud-PostTrait.html#method_findAndReplaceDocument"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\PostTrait\u003A\u003AgetDocumentThumbnails\u0028\u0029",
            "name": "getDocumentThumbnails",
            "summary": "Generate\u0020a\u0020thumbnail\u0020image\u0020per\u0020page\u0020of\u0020specified\u0020document\u0020filename.",
            "url": "classes/TextControl-ReportingCloud-PostTrait.html#method_getDocumentThumbnails"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\PostTrait\u003A\u003AgetTrackedChanges\u0028\u0029",
            "name": "getTrackedChanges",
            "summary": "Return\u0020the\u0020tracked\u0020changes\u0020in\u0020a\u0020document.",
            "url": "classes/TextControl-ReportingCloud-PostTrait.html#method_getTrackedChanges"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\PostTrait\u003A\u003AremoveTrackedChange\u0028\u0029",
            "name": "removeTrackedChange",
            "summary": "Removes\u0020a\u0020specific\u0020tracked\u0020change\u0020and\u0020returns\u0020the\u0020resulting\u0020document.",
            "url": "classes/TextControl-ReportingCloud-PostTrait.html#method_removeTrackedChange"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\PostTrait\u003A\u003Auri\u0028\u0029",
            "name": "uri",
            "summary": "Construct\u0020URI\u0020with\u0020version\u0020number",
            "url": "classes/TextControl-ReportingCloud-PostTrait.html#method_uri"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\PostTrait\u003A\u003Arequest\u0028\u0029",
            "name": "request",
            "summary": "Request\u0020the\u0020URI\u0020with\u0020options",
            "url": "classes/TextControl-ReportingCloud-PostTrait.html#method_request"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\PostTrait\u003A\u003AbuildFindAndReplaceDataArray\u0028\u0029",
            "name": "buildFindAndReplaceDataArray",
            "summary": "Using\u0020passed\u0020findAndReplaceData\u0020associative\u0020array\u0020\u0028key\u002Dvalue\u0029,\u0020build\u0020array\u0020for\u0020backend\u0020\u0028list\u0020of\u0020string\u0020arrays\u0029",
            "url": "classes/TextControl-ReportingCloud-PostTrait.html#method_buildFindAndReplaceDataArray"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\PostTrait\u003A\u003AbuildMergeSettingsArray\u0028\u0029",
            "name": "buildMergeSettingsArray",
            "summary": "Using\u0020passed\u0020mergeSettings\u0020array,\u0020build\u0020array\u0020for\u0020backend",
            "url": "classes/TextControl-ReportingCloud-PostTrait.html#method_buildMergeSettingsArray"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\PostTrait\u003A\u003AbuildDocumentsArray\u0028\u0029",
            "name": "buildDocumentsArray",
            "summary": "Using\u0020passed\u0020documentsData\u0020array,\u0020build\u0020array\u0020for\u0020backend",
            "url": "classes/TextControl-ReportingCloud-PostTrait.html#method_buildDocumentsArray"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\PostTrait\u003A\u003AbuildDocumentSettingsArray\u0028\u0029",
            "name": "buildDocumentSettingsArray",
            "summary": "Using\u0020passed\u0020documentsSettings\u0020array,\u0020build\u0020array\u0020for\u0020backend",
            "url": "classes/TextControl-ReportingCloud-PostTrait.html#method_buildDocumentSettingsArray"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\PostTrait\u003A\u003AbuildPropertyMapArray\u0028\u0029",
            "name": "buildPropertyMapArray",
            "summary": "Using\u0020the\u0020passed\u0020propertyMap,\u0020recursively\u0020build\u0020array",
            "url": "classes/TextControl-ReportingCloud-PostTrait.html#method_buildPropertyMapArray"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\PostTrait\u003A\u003Apost\u0028\u0029",
            "name": "post",
            "summary": "Execute\u0020a\u0020POST\u0020request\u0020via\u0020REST\u0020client",
            "url": "classes/TextControl-ReportingCloud-PostTrait.html#method_post"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\PropertyMap\\AbstractPropertyMap",
            "name": "AbstractPropertyMap",
            "summary": "Abstract\u0020AbstractPropertyMap",
            "url": "classes/TextControl-ReportingCloud-PropertyMap-AbstractPropertyMap.html"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\PropertyMap\\AbstractPropertyMap\u003A\u003AgetMap\u0028\u0029",
            "name": "getMap",
            "summary": "Return\u0020the\u0020property\u0020map",
            "url": "classes/TextControl-ReportingCloud-PropertyMap-AbstractPropertyMap.html#method_getMap"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\PropertyMap\\AbstractPropertyMap\u003A\u003AsetMap\u0028\u0029",
            "name": "setMap",
            "summary": "Set\u0020the\u0020property\u0020map",
            "url": "classes/TextControl-ReportingCloud-PropertyMap-AbstractPropertyMap.html#method_setMap"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\PropertyMap\\AbstractPropertyMap\u003A\u003A\u0024map",
            "name": "map",
            "summary": "Assoc\u0020array\u0020of\u0020properties\ncamelCase\u0020properties\u0020\u003D\u003E\u0020Lower\u0020case\u0020underscore\u0020array\u0020keys",
            "url": "classes/TextControl-ReportingCloud-PropertyMap-AbstractPropertyMap.html#property_map"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\PropertyMap\\AccountSettings",
            "name": "AccountSettings",
            "summary": "AccountSettings\u0020property\u0020map",
            "url": "classes/TextControl-ReportingCloud-PropertyMap-AccountSettings.html"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\PropertyMap\\AccountSettings\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Set\u0020the\u0020property\u0020map\u0020of\u0020AccountSettings",
            "url": "classes/TextControl-ReportingCloud-PropertyMap-AccountSettings.html#method___construct"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\PropertyMap\\ApiKey",
            "name": "ApiKey",
            "summary": "ApiKey\u0020property\u0020map",
            "url": "classes/TextControl-ReportingCloud-PropertyMap-ApiKey.html"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\PropertyMap\\ApiKey\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Set\u0020the\u0020property\u0020map\u0020of\u0020ApiKey",
            "url": "classes/TextControl-ReportingCloud-PropertyMap-ApiKey.html#method___construct"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\PropertyMap\\DocumentSettings",
            "name": "DocumentSettings",
            "summary": "DocumentSettings\u0020property\u0020map",
            "url": "classes/TextControl-ReportingCloud-PropertyMap-DocumentSettings.html"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\PropertyMap\\DocumentSettings\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Set\u0020the\u0020property\u0020map\u0020of\u0020DocumentSettings",
            "url": "classes/TextControl-ReportingCloud-PropertyMap-DocumentSettings.html#method___construct"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\PropertyMap\\IncorrectWord",
            "name": "IncorrectWord",
            "summary": "IncorrectWord\u0020property\u0020map",
            "url": "classes/TextControl-ReportingCloud-PropertyMap-IncorrectWord.html"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\PropertyMap\\IncorrectWord\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Set\u0020the\u0020property\u0020map\u0020of\u0020IncorrectWord",
            "url": "classes/TextControl-ReportingCloud-PropertyMap-IncorrectWord.html#method___construct"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\PropertyMap\\MergeSettings",
            "name": "MergeSettings",
            "summary": "MergeSettings\u0020property\u0020map",
            "url": "classes/TextControl-ReportingCloud-PropertyMap-MergeSettings.html"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\PropertyMap\\MergeSettings\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Set\u0020the\u0020property\u0020map\u0020of\u0020MergeSettings",
            "url": "classes/TextControl-ReportingCloud-PropertyMap-MergeSettings.html#method___construct"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\PropertyMap\\ModifiedDocument",
            "name": "ModifiedDocument",
            "summary": "ModifiedDocument\u0020property\u0020map",
            "url": "classes/TextControl-ReportingCloud-PropertyMap-ModifiedDocument.html"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\PropertyMap\\ModifiedDocument\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Set\u0020the\u0020property\u0020map\u0020of\u0020ModifiedDocument",
            "url": "classes/TextControl-ReportingCloud-PropertyMap-ModifiedDocument.html#method___construct"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\PropertyMap\\PropertyMapInterface",
            "name": "PropertyMapInterface",
            "summary": "Property\u0020map\u0020interface",
            "url": "classes/TextControl-ReportingCloud-PropertyMap-PropertyMapInterface.html"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\PropertyMap\\PropertyMapInterface\u003A\u003AgetMap\u0028\u0029",
            "name": "getMap",
            "summary": "Return\u0020the\u0020property\u0020map",
            "url": "classes/TextControl-ReportingCloud-PropertyMap-PropertyMapInterface.html#method_getMap"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\PropertyMap\\PropertyMapInterface\u003A\u003AsetMap\u0028\u0029",
            "name": "setMap",
            "summary": "Set\u0020the\u0020property\u0020map",
            "url": "classes/TextControl-ReportingCloud-PropertyMap-PropertyMapInterface.html#method_setMap"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\PropertyMap\\TemplateInfo",
            "name": "TemplateInfo",
            "summary": "TemplateInfo\u0020property\u0020map",
            "url": "classes/TextControl-ReportingCloud-PropertyMap-TemplateInfo.html"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\PropertyMap\\TemplateInfo\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Set\u0020the\u0020property\u0020map\u0020of\u0020TemplateInfo",
            "url": "classes/TextControl-ReportingCloud-PropertyMap-TemplateInfo.html#method___construct"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\PropertyMap\\TemplateList",
            "name": "TemplateList",
            "summary": "TemplateList\u0020property\u0020map",
            "url": "classes/TextControl-ReportingCloud-PropertyMap-TemplateList.html"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\PropertyMap\\TemplateList\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Set\u0020the\u0020property\u0020map\u0020of\u0020TemplateList",
            "url": "classes/TextControl-ReportingCloud-PropertyMap-TemplateList.html#method___construct"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\PropertyMap\\TrackedChanges",
            "name": "TrackedChanges",
            "summary": "TrackedChanges\u0020property\u0020map",
            "url": "classes/TextControl-ReportingCloud-PropertyMap-TrackedChanges.html"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\PropertyMap\\TrackedChanges\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Set\u0020the\u0020property\u0020map\u0020of\u0020TrackedChanges",
            "url": "classes/TextControl-ReportingCloud-PropertyMap-TrackedChanges.html#method___construct"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\PutTrait",
            "name": "PutTrait",
            "summary": "Trait\u0020PutTrait",
            "url": "classes/TextControl-ReportingCloud-PutTrait.html"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\PutTrait\u003A\u003AcreateApiKey\u0028\u0029",
            "name": "createApiKey",
            "summary": "Create\u0020an\u0020API\u0020key",
            "url": "classes/TextControl-ReportingCloud-PutTrait.html#method_createApiKey"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\PutTrait\u003A\u003Auri\u0028\u0029",
            "name": "uri",
            "summary": "Construct\u0020URI\u0020with\u0020version\u0020number",
            "url": "classes/TextControl-ReportingCloud-PutTrait.html#method_uri"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\PutTrait\u003A\u003Arequest\u0028\u0029",
            "name": "request",
            "summary": "Request\u0020the\u0020URI\u0020with\u0020options",
            "url": "classes/TextControl-ReportingCloud-PutTrait.html#method_request"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\PutTrait\u003A\u003AbuildPropertyMapArray\u0028\u0029",
            "name": "buildPropertyMapArray",
            "summary": "Using\u0020the\u0020passed\u0020propertyMap,\u0020recursively\u0020build\u0020array",
            "url": "classes/TextControl-ReportingCloud-PutTrait.html#method_buildPropertyMapArray"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\PutTrait\u003A\u003Aput\u0028\u0029",
            "name": "put",
            "summary": "Execute\u0020a\u0020PUT\u0020request\u0020via\u0020REST\u0020client",
            "url": "classes/TextControl-ReportingCloud-PutTrait.html#method_put"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\ReportingCloud",
            "name": "ReportingCloud",
            "summary": "Abstract\u0020ReportingCloud",
            "url": "classes/TextControl-ReportingCloud-ReportingCloud.html"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\ReportingCloud\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/TextControl-ReportingCloud-ReportingCloud.html#method___construct"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Stdlib\\AbstractStdlib",
            "name": "AbstractStdlib",
            "summary": "Abstract\u0020StdlibAbstract",
            "url": "classes/TextControl-ReportingCloud-Stdlib-AbstractStdlib.html"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Stdlib\\ArrayUtils",
            "name": "ArrayUtils",
            "summary": "Abstract\u0020StdlibAbstract",
            "url": "classes/TextControl-ReportingCloud-Stdlib-ArrayUtils.html"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Stdlib\\ArrayUtils\u003A\u003AvarExportToFile\u0028\u0029",
            "name": "varExportToFile",
            "summary": "Write\u0020the\u0020array\u0020of\u0020passed\u0020data\u0020to\u0020a\u0020file\u0020as\u0020a\u0020PHP\u0020structure",
            "url": "classes/TextControl-ReportingCloud-Stdlib-ArrayUtils.html#method_varExportToFile"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Stdlib\\ConsoleUtils",
            "name": "ConsoleUtils",
            "summary": "ReportingCloud\u0020console\u0020helper\u0020\u0028used\u0020only\u0020for\u0020tests\u0020and\u0020demos\u0029",
            "url": "classes/TextControl-ReportingCloud-Stdlib-ConsoleUtils.html"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Stdlib\\ConsoleUtils\u003A\u003AcheckCredentials\u0028\u0029",
            "name": "checkCredentials",
            "summary": "Check\u0020that\u0020either\u0020the\u0020API\u0020key\u0020has\u0020been\u0020defined\u0020in\u0020environment\u0020variables",
            "url": "classes/TextControl-ReportingCloud-Stdlib-ConsoleUtils.html#method_checkCredentials"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Stdlib\\ConsoleUtils\u003A\u003AapiKey\u0028\u0029",
            "name": "apiKey",
            "summary": "Return\u0020the\u0020ReportingCloud\u0020API\u0020key\u0020from\u0020a\u0020PHP\u0020constant\u0020or\u0020environmental\u0020variable",
            "url": "classes/TextControl-ReportingCloud-Stdlib-ConsoleUtils.html#method_apiKey"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Stdlib\\ConsoleUtils\u003A\u003AbaseUri\u0028\u0029",
            "name": "baseUri",
            "summary": "Return\u0020the\u0020ReportingCloud\u0020base\u0020URI\u0020from\u0020a\u0020PHP\u0020constant\u0020or\u0020environmental\u0020variable",
            "url": "classes/TextControl-ReportingCloud-Stdlib-ConsoleUtils.html#method_baseUri"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Stdlib\\ConsoleUtils\u003A\u003AerrorMessage\u0028\u0029",
            "name": "errorMessage",
            "summary": "Return\u0020error\u0020message\u0020explaining\u0020how\u0020to\u0020configure\u0020PHP\u0020constant\u0020or\u0020environmental\u0020variables",
            "url": "classes/TextControl-ReportingCloud-Stdlib-ConsoleUtils.html#method_errorMessage"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Stdlib\\ConsoleUtils\u003A\u003Adump\u0028\u0029",
            "name": "dump",
            "summary": "Dump\u0020information\u0020about\u0020a\u0020variable",
            "url": "classes/TextControl-ReportingCloud-Stdlib-ConsoleUtils.html#method_dump"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Stdlib\\ConsoleUtils\u003A\u003AwriteLn\u0028\u0029",
            "name": "writeLn",
            "summary": "Write\u0020a\u0020line\u0020to\u0020the\u0020console",
            "url": "classes/TextControl-ReportingCloud-Stdlib-ConsoleUtils.html#method_writeLn"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Stdlib\\ConsoleUtils\u003A\u003AgetValueFromConstOrEnvVar\u0028\u0029",
            "name": "getValueFromConstOrEnvVar",
            "summary": "Return\u0020a\u0020value\u0020from\u0020a\u0020PHP\u0020constant\u0020or\u0020environmental\u0020variable",
            "url": "classes/TextControl-ReportingCloud-Stdlib-ConsoleUtils.html#method_getValueFromConstOrEnvVar"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Stdlib\\ConsoleUtils\u003A\u003AgetValueFromConst\u0028\u0029",
            "name": "getValueFromConst",
            "summary": "Return\u0020a\u0020value\u0020from\u0020a\u0020PHP\u0020constant",
            "url": "classes/TextControl-ReportingCloud-Stdlib-ConsoleUtils.html#method_getValueFromConst"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Stdlib\\ConsoleUtils\u003A\u003AgetValueFromEnvVar\u0028\u0029",
            "name": "getValueFromEnvVar",
            "summary": "Return\u0020a\u0020value\u0020from\u0020an\u0020environmental\u0020variable",
            "url": "classes/TextControl-ReportingCloud-Stdlib-ConsoleUtils.html#method_getValueFromEnvVar"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Stdlib\\ConsoleUtils\u003A\u003AAPI_KEY",
            "name": "API_KEY",
            "summary": "Name\u0020of\u0020PHP\u0020constant\u0020or\u0020environmental\u0020variable\u0020storing\u0020API\u0020key",
            "url": "classes/TextControl-ReportingCloud-Stdlib-ConsoleUtils.html#constant_API_KEY"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Stdlib\\ConsoleUtils\u003A\u003ABASE_URI",
            "name": "BASE_URI",
            "summary": "Name\u0020of\u0020PHP\u0020constant\u0020or\u0020environmental\u0020variable\u0020storing\u0020base\u0020URI",
            "url": "classes/TextControl-ReportingCloud-Stdlib-ConsoleUtils.html#constant_BASE_URI"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Stdlib\\FileUtils",
            "name": "FileUtils",
            "summary": "Abstract\u0020StdlibAbstract",
            "url": "classes/TextControl-ReportingCloud-Stdlib-FileUtils.html"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Stdlib\\FileUtils\u003A\u003Aread\u0028\u0029",
            "name": "read",
            "summary": "Read\u0020a\u0020filename\u0020from\u0020filesystem\u0020and\u0020return\u0020its\u0020binary\u0020data.",
            "url": "classes/TextControl-ReportingCloud-Stdlib-FileUtils.html#method_read"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Stdlib\\FileUtils\u003A\u003Awrite\u0028\u0029",
            "name": "write",
            "summary": "Write\u0020binary\u0020data\u0020to\u0020a\u0020filename\u0020on\u0020filesystem.",
            "url": "classes/TextControl-ReportingCloud-Stdlib-FileUtils.html#method_write"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Stdlib\\Path",
            "name": "Path",
            "summary": "",
            "url": "classes/TextControl-ReportingCloud-Stdlib-Path.html"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Stdlib\\Path\u003A\u003Aroot\u0028\u0029",
            "name": "root",
            "summary": "Return\u0020the\u0020root\u0020path\u0020of\u0020PHP\u0020SDK\u0020for\u0020ReportingCloud\u0020Web\u0020API",
            "url": "classes/TextControl-ReportingCloud-Stdlib-Path.html#method_root"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Stdlib\\Path\u003A\u003Abin\u0028\u0029",
            "name": "bin",
            "summary": "Return\u0020the\u0020binary\u0020path\u0020of\u0020PHP\u0020SDK\u0020for\u0020ReportingCloud\u0020Web\u0020API",
            "url": "classes/TextControl-ReportingCloud-Stdlib-Path.html#method_bin"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Stdlib\\Path\u003A\u003Adata\u0028\u0029",
            "name": "data",
            "summary": "Return\u0020the\u0020data\u0020path\u0020of\u0020PHP\u0020SDK\u0020for\u0020ReportingCloud\u0020Web\u0020API",
            "url": "classes/TextControl-ReportingCloud-Stdlib-Path.html#method_data"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Stdlib\\Path\u003A\u003Ademo\u0028\u0029",
            "name": "demo",
            "summary": "Return\u0020the\u0020demo\u0020path\u0020of\u0020PHP\u0020SDK\u0020for\u0020ReportingCloud\u0020Web\u0020API",
            "url": "classes/TextControl-ReportingCloud-Stdlib-Path.html#method_demo"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Stdlib\\Path\u003A\u003Aoutput\u0028\u0029",
            "name": "output",
            "summary": "Return\u0020the\u0020output\u0020path\u0020of\u0020PHP\u0020SDK\u0020for\u0020ReportingCloud\u0020Web\u0020API",
            "url": "classes/TextControl-ReportingCloud-Stdlib-Path.html#method_output"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Stdlib\\Path\u003A\u003Aresource\u0028\u0029",
            "name": "resource",
            "summary": "Return\u0020the\u0020resources\u0020path\u0020of\u0020PHP\u0020SDK\u0020for\u0020ReportingCloud\u0020Web\u0020API",
            "url": "classes/TextControl-ReportingCloud-Stdlib-Path.html#method_resource"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Stdlib\\Path\u003A\u003Atest\u0028\u0029",
            "name": "test",
            "summary": "Return\u0020the\u0020rest\u0020path\u0020of\u0020PHP\u0020SDK\u0020for\u0020ReportingCloud\u0020Web\u0020API",
            "url": "classes/TextControl-ReportingCloud-Stdlib-Path.html#method_test"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud",
            "name": "ReportingCloud",
            "summary": "",
            "url": "namespaces/textcontrol-reportingcloud.html"
        },                {
            "fqsen": "\\TextControl",
            "name": "TextControl",
            "summary": "",
            "url": "namespaces/textcontrol.html"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Assert",
            "name": "Assert",
            "summary": "",
            "url": "namespaces/textcontrol-reportingcloud-assert.html"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Exception",
            "name": "Exception",
            "summary": "",
            "url": "namespaces/textcontrol-reportingcloud-exception.html"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Filter",
            "name": "Filter",
            "summary": "",
            "url": "namespaces/textcontrol-reportingcloud-filter.html"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\PropertyMap",
            "name": "PropertyMap",
            "summary": "",
            "url": "namespaces/textcontrol-reportingcloud-propertymap.html"
        },                {
            "fqsen": "\\TextControl\\ReportingCloud\\Stdlib",
            "name": "Stdlib",
            "summary": "",
            "url": "namespaces/textcontrol-reportingcloud-stdlib.html"
        }            ]
);
